//! Compact built-in base/recommended export floor used only when installed R
//! packages and base-exports sidecars are unavailable.

use std::collections::HashSet;

const BASE_EXPORTS: &[&str] = &[
    "::",
    ":::",
    "[",
    "[[",
    "$",
    "<-",
    "=",
    "{",
    "(",
    "if",
    "for",
    "while",
    "repeat",
    "function",
    "break",
    "next",
    "TRUE",
    "FALSE",
    "NULL",
    "NA",
    "NaN",
    "Inf",
    "print",
    "cat",
    "sum",
    "mean",
    "median",
    "min",
    "max",
    "length",
    "seq",
    "seq_len",
    "seq_along",
    "c",
    "list",
    "data.frame",
    "matrix",
    "array",
    "factor",
    "as.character",
    "as.numeric",
    "as.integer",
    "as.logical",
    "is.na",
    "is.null",
    "isTRUE",
    "stop",
    "warning",
    "message",
    "library",
    "require",
    "source",
    "get",
    "exists",
    "assign",
    "ls",
    "rm",
    "paste",
    "paste0",
    "sprintf",
    "format",
    "names",
    "colnames",
    "rownames",
    "nrow",
    "ncol",
    "dim",
    "str",
    "summary",
    "head",
    "tail",
    "help",
    "set.seed",
    "sample",
    "runif",
    "rnorm",
    "dnorm",
    "pnorm",
    "qnorm",
    "lm",
    "glm",
    "predict",
    "plot",
    "hist",
    "lines",
    "points",
    "title",
];

const BASE_DATASETS: &[&str] = &[
    "AirPassengers",
    "BOD",
    "CO2",
    "ChickWeight",
    "DNase",
    "EuStockMarkets",
    "Formaldehyde",
    "HairEyeColor",
    "InsectSprays",
    "JohnsonJohnson",
    "LakeHuron",
    "LifeCycleSavings",
    "Loblolly",
    "Nile",
    "Orange",
    "OrchardSprays",
    "PlantGrowth",
    "Puromycin",
    "Theoph",
    "Titanic",
    "ToothGrowth",
    "UCBAdmissions",
    "UKDriverDeaths",
    "UKgas",
    "USAccDeaths",
    "USArrests",
    "USJudgeRatings",
    "USPersonalExpenditure",
    "UScitiesD",
    "VADeaths",
    "WWWusage",
    "WorldPhones",
    "airmiles",
    "airquality",
    "anscombe",
    "attenu",
    "attitude",
    "austres",
    "beaver1",
    "beaver2",
    "cars",
    "chickwts",
    "co2",
    "crimtab",
    "discoveries",
    "esoph",
    "euro",
    "euro.cross",
    "eurodist",
    "faithful",
    "fdeaths",
    "freeny",
    "infert",
    "iris",
    "iris3",
    "islands",
    "ldeaths",
    "lh",
    "longley",
    "lynx",
    "mdeaths",
    "morley",
    "mtcars",
    "nhtemp",
    "nottem",
    "occupationalStatus",
    "precip",
    "presidents",
    "pressure",
    "quakes",
    "randu",
    "rivers",
    "rock",
    "sleep",
    "stack.loss",
    "stack.x",
    "stackloss",
    "state.abb",
    "state.area",
    "state.center",
    "state.division",
    "state.name",
    "state.region",
    "state.x77",
    "sunspot.month",
    "sunspot.year",
    "sunspots",
    "swiss",
    "treering",
    "trees",
    "uspop",
    "volcano",
    "warpbreaks",
    "women",
];

const BASE_PACKAGES: &[&str] = &[
    "base",
    "methods",
    "utils",
    "grDevices",
    "graphics",
    "stats",
    "datasets",
];

pub fn load() -> (HashSet<String>, HashSet<String>) {
    let exports = BASE_EXPORTS
        .iter()
        .chain(BASE_DATASETS.iter())
        .map(|s| (*s).to_string())
        .collect();
    let packages = BASE_PACKAGES.iter().map(|s| (*s).to_string()).collect();
    (exports, packages)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn load_includes_common_platform_floor() {
        let (exports, packages) = load();
        let canonical_packages: HashSet<String> = crate::r_subprocess::get_fallback_base_packages()
            .into_iter()
            .collect();

        assert!(exports.contains("print"));
        assert!(exports.contains("mtcars"));
        assert_eq!(packages, canonical_packages);
        assert!(packages.contains("base"));
        assert!(packages.contains("datasets"));
    }
}
