//! Tier 2 encoding: a committed, deterministic, diff-friendly `.raven/packages.json`.

use std::collections::HashMap;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::package_db::model::PackageRecord;
use crate::package_db::PackageMetadataProvider;
use crate::package_library::PackageInfo;

/// Tier 2 schema version. Bump when the on-disk shape changes incompatibly.
pub const REPO_DB_SCHEMA_VERSION: u32 = 1;

/// Typed error so a present-but-unusable Tier 2 file can be explained, not
/// silently dropped (decision #9).
#[derive(Debug)]
pub enum RepoDbError {
    /// File is not present — normal, callers stay silent.
    Absent,
    /// File present but written by an incompatible schema.
    UnsupportedSchema { found: u32, supported: u32 },
    /// File present but unparseable / corrupt.
    Corrupt(String),
}

impl std::fmt::Display for RepoDbError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RepoDbError::Absent => write!(f, "no .raven/packages.json present"),
            RepoDbError::UnsupportedSchema { found, supported } => write!(
                f,
                ".raven/packages.json was generated by a newer Raven (schema v{found}); \
                 this Raven understands schema v{supported}. Upgrade Raven here, or regenerate \
                 with `raven packages freeze`. Falling back to the bundled database."
            ),
            RepoDbError::Corrupt(d) => write!(f, ".raven/packages.json is unreadable: {d}"),
        }
    }
}

/// Minimal provenance recorded in the Tier 2 file — for debuggability only.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RepoDbProvenance {
    pub raven_version: String,
    pub r_version: String,
    /// Generation time as Unix epoch seconds.
    pub generated_unix: u64,
}

/// The full Tier 2 document.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RepoDb {
    /// Schema version (first field so it leads the JSON). Checked on read.
    pub schema_version: u32,
    pub provenance: RepoDbProvenance,
    /// Sorted by package name on write for deterministic, diff-friendly output.
    pub packages: Vec<PackageRecord>,
}

/// Serialize to the canonical pretty JSON string. Packages are sorted by name.
pub fn write_repo_db_string(db: &RepoDb) -> String {
    let mut sorted = db.clone();
    sorted.packages.sort_by(|a, b| a.name.cmp(&b.name));
    serde_json::to_string_pretty(&sorted).expect("RepoDb serializes")
}

/// Write the canonical JSON to `path`, creating the parent directory.
pub fn write_repo_db_file(path: &Path, db: &RepoDb) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut text = write_repo_db_string(db);
    text.push('\n'); // trailing newline for clean diffs
    std::fs::write(path, text)
}

/// Parse a Tier 2 document from a string. Maps a schema mismatch to
/// `UnsupportedSchema` and any other serde failure to `Corrupt`.
pub fn read_repo_db_str(text: &str) -> Result<RepoDb, RepoDbError> {
    let db: RepoDb = serde_json::from_str(text).map_err(|e| RepoDbError::Corrupt(e.to_string()))?;
    if db.schema_version > REPO_DB_SCHEMA_VERSION {
        return Err(RepoDbError::UnsupportedSchema {
            found: db.schema_version,
            supported: REPO_DB_SCHEMA_VERSION,
        });
    }
    Ok(db)
}

/// Parse a Tier 2 document from a file path. A missing file maps to `Absent`.
pub fn read_repo_db_file(path: &Path) -> Result<RepoDb, RepoDbError> {
    match std::fs::read_to_string(path) {
        Ok(text) => read_repo_db_str(&text),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Err(RepoDbError::Absent),
        Err(e) => Err(RepoDbError::Corrupt(e.to_string())),
    }
}

/// Tier 2 provider: an in-memory map over a loaded `RepoDb`.
pub struct RepoDbProvider {
    by_name: HashMap<String, PackageRecord>,
}

impl RepoDbProvider {
    pub fn from_db(db: RepoDb) -> Self {
        let by_name = db.packages.into_iter().map(|r| (r.name.clone(), r)).collect();
        Self { by_name }
    }

    /// Load from a `.raven/packages.json` file. Returns `Ok(None)` when the file
    /// is simply absent (normal, silent); `Err(e)` for the loud cases
    /// (`UnsupportedSchema`/`Corrupt`) so the caller can explain-and-continue.
    pub fn from_file(path: &Path) -> Result<Option<Self>, RepoDbError> {
        match read_repo_db_file(path) {
            Ok(db) => Ok(Some(Self::from_db(db))),
            Err(RepoDbError::Absent) => Ok(None),
            Err(e) => Err(e),
        }
    }
}

impl PackageMetadataProvider for RepoDbProvider {
    fn lookup(&self, name: &str) -> Option<PackageInfo> {
        self.by_name.get(name).map(|r| r.clone().into_info())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::package_db::model::PackageRecord;

    fn sample() -> RepoDb {
        RepoDb {
            schema_version: REPO_DB_SCHEMA_VERSION,
            provenance: RepoDbProvenance {
                raven_version: "9.9.9".into(),
                r_version: "4.4.0".into(),
                generated_unix: 1_700_000_000,
            },
            // intentionally out of order to prove the writer sorts.
            packages: vec![
                PackageRecord { name: "dplyr".into(), version: "1.1.4".into(), exports: vec!["mutate".into()], depends: vec![], lazy_data: vec![] },
                PackageRecord { name: "cli".into(), version: "3.6.2".into(), exports: vec!["cli_alert".into()], depends: vec![], lazy_data: vec![] },
            ],
        }
    }

    #[test]
    fn write_then_read_round_trips() {
        let db = sample();
        let text = write_repo_db_string(&db);
        let parsed = read_repo_db_str(&text).unwrap();
        assert_eq!(parsed.packages.len(), 2);
        assert_eq!(parsed.packages[0].name, "cli");
        assert_eq!(parsed.packages[1].name, "dplyr");
        assert_eq!(parsed.packages[1].version, "1.1.4");
        assert_eq!(parsed.provenance.r_version, "4.4.0");
        assert_eq!(parsed.schema_version, REPO_DB_SCHEMA_VERSION);
    }

    #[test]
    fn write_is_deterministic_for_same_content() {
        let a = write_repo_db_string(&sample());
        let b = write_repo_db_string(&sample());
        assert_eq!(a, b, "same content must serialize to identical bytes");
    }

    #[test]
    fn newer_schema_is_rejected_with_unsupported() {
        // A document written by a newer Raven (schema 999) must be flagged, not silently parsed.
        let mut text = write_repo_db_string(&sample());
        text = text.replace("\"schema_version\": 1", "\"schema_version\": 999");
        match read_repo_db_str(&text) {
            Err(RepoDbError::UnsupportedSchema { found, supported }) => {
                assert_eq!(found, 999);
                assert_eq!(supported, REPO_DB_SCHEMA_VERSION);
            }
            other => panic!("expected UnsupportedSchema, got {other:?}"),
        }
    }
}
